name:                anki-haskell
version:             0.1.0.0
github:              "bchase/anki-haskell"
license:             BSD3
author:              "Brad Chase"
maintainer:          "brad@these8bits.com"
copyright:           "2018 Brad Chase"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/bchase/anki-haskell#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -Werror
  dependencies:
    - aeson >= 1.2.4.0 && < 1.2.5
    - bytestring
    - containers
    - cryptonite >= 0.25 && < 0.26
    - directory
    - filepath
    - random
    - sqlite-simple >= 0.4.16.0 && < 0.4.17
    - text
    - time
    - transformers >= 0.5.2.0 && < 0.5.3
    - unordered-containers
    - zip >= 1.0.0 && < 1.1

executables:
  anki-haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - anki-haskell

tests:
  anki-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - anki-haskell
